package io.github.godogx.godog

import com.intellij.openapi.Disposable
import com.intellij.openapi.application.ApplicationManager
import com.intellij.openapi.components.Service
import com.intellij.openapi.module.Module
import com.intellij.openapi.project.Project
import com.intellij.openapi.roots.ProjectFileIndex
import com.intellij.openapi.roots.ProjectRootManager
import com.intellij.openapi.vfs.VfsUtilCore
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.openapi.vfs.VirtualFileManager
import com.intellij.openapi.vfs.VirtualFileVisitor
import com.intellij.openapi.vfs.newvfs.BulkFileListener
import com.intellij.openapi.vfs.newvfs.events.VFileEvent
import java.util.concurrent.ConcurrentHashMap

internal const val STEPS_FILE_NAME = ".godog-gherkin.json"

/**
 * Tracks every .godog-gherkin.json under this project's content.
 *
 * godog projects routinely .gitignore this file (it's a build artifact regenerated by each
 * `go test` run), and IntelliJ's file-based indexes (FilenameIndex included) skip VCS-ignored
 * files - so this can't be a FilenameIndex lookup. It also can't be a fresh directory walk on
 * every call: [GodogStepsIndex] used to do that, keyed on "any PSI change anywhere", which
 * doesn't scale past a small repo (a walk of the whole content tree on every keystroke). So:
 * walk once lazily, then stay current via VFS_CHANGES instead of walking again.
 */
@Service(Service.Level.PROJECT)
class GodogStepsFileTracker(private val project: Project) : Disposable {
    private val files = ConcurrentHashMap.newKeySet<VirtualFile>()
    private val initLock = Any()
    @Volatile private var initialized = false

    init {
        ApplicationManager.getApplication().messageBus.connect(this).subscribe(
            VirtualFileManager.VFS_CHANGES,
            object : BulkFileListener {
                override fun after(events: List<VFileEvent>) {
                    val fileIndex = ProjectFileIndex.getInstance(project)
                    for (event in events) {
                        val file = event.file ?: continue
                        val tracked = file.isValid && !file.isDirectory &&
                            file.name == STEPS_FILE_NAME && fileIndex.isInContent(file)
                        if (tracked) files.add(file) else files.remove(file)
                    }
                }
            },
        )
    }

    /** All tracked .godog-gherkin.json files that belong to [module]'s content. */
    fun filesFor(module: Module): List<VirtualFile> {
        ensureInitialized()
        val fileIndex = ProjectFileIndex.getInstance(project)
        return files.filter { it.isValid && fileIndex.getModuleForFile(it) == module }
    }

    private fun ensureInitialized() {
        if (initialized) return
        synchronized(initLock) {
            if (initialized) return
            for (root in ProjectRootManager.getInstance(project).contentRoots) {
                VfsUtilCore.visitChildrenRecursively(root, object : VirtualFileVisitor<Unit>() {
                    override fun visitFile(file: VirtualFile): Boolean {
                        if (!file.isDirectory && file.name == STEPS_FILE_NAME) files.add(file)
                        return true
                    }
                })
            }
            initialized = true
        }
    }

    override fun dispose() {}
}
